In [1]:
from dotenv import load_dotenv

load_dotenv("../.env")

True

In [3]:
import numpy as np
from numpy import dot
from numpy.linalg import norm
import pandas as pd
from langchain_openai import OpenAI, OpenAIEmbeddings

/Users/choyoungrae/Desktop/book-study/books/RAG 마스터 랭체인으로 완성하는 LLM 서비스/rag-master-practice-260326/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
embeddings = OpenAIEmbeddings(model="text-embedding-ada-002")
query_result = embeddings.embed_query("저는 배가 고파요")
print(query_result)

[-0.01663108356297016, -0.021850483492016792, 0.015224344097077847, -0.027161912992596626, -0.03681188449263573, 0.01172721479088068, -0.034550584852695465, -0.006731315981596708, -0.02394087240099907, -0.016815142706036568, -0.008124909363687038, 0.010826637968420982, -0.010504534468054771, -0.022626161575317383, 0.011326228268444538, -0.004890721756964922, 0.012075613252818584, -0.002912083175033331, 0.008216938935220242, -0.01613149419426918, 0.0013837324222549796, -0.014566988684237003, 0.018274471163749695, -0.012634364888072014, 0.003244047285988927, 0.006389491725713015, 0.0053311497904360294, -0.019037002697587013, -0.009235839359462261, -0.0017962227575480938, 0.03452428802847862, -0.016499612480401993, 0.00013054661394562572, 0.0031191499438136816, 0.007382097654044628, -0.0055086356587708, -0.006382917985320091, 0.00344125390984118, -0.0038849685806781054, -0.0021955659613013268, -0.02238951437175274, -0.010373063385486603, 0.01129993423819542, -0.024769140407443047, 0.013232558034360409, 0.009091220796108246, -0.010596564039587975, -0.025479083880782127, -0.020088771358132362, 0.016433877870440483, 0.014290899969637394, -0.016078906133770943, -0.007848819717764854, -0.017498793080449104, 0.0008290891419164836, 0.027004146948456764, -0.009571090340614319, -0.0007296641706489027, 0.004470014479011297, -0.014159428887069225, 0.004765824414789677, 0.0203517135232687, -0.01376501563936472, 0.011871833354234695, -0.010287607088685036, 0.007881687954068184, 0.022244896739721298, 0.0028808587230741978, -0.023835696280002594, 0.006350050214678049, 0.01802467741072178, 0.04178148880600929, -0.02062780223786831, -0.008742822334170341, 0.03197375312447548, -0.0068496400490403175, -0.009860326535999775, 0.0003192280710209161, -0.0316845141351223, 0.014054251834750175, 0.031079748645424843, -0.022363219410181046, 0.0015357458032667637, 0.009590811096131802, 0.009091220796108246, 0.011773229576647282, -0.0329466387629509, 0.015079725533723831, -0.034261345863342285, -0.005784724839031696, 0.005350870545953512, 0.024111784994602203, -0.010944962501525879, 0.03597047179937363, 0.0056762611493468285, 0.008769117295742035, -0.012023024260997772, 0.03470834717154503, -0.008440439589321613, -0.01823502965271473, 0.001238292665220797, -0.005239120218902826, -0.019562887027859688, -0.009268706664443016, -0.03071163035929203, -0.0050714947283267975, 0.019746946170926094, 0.008203791454434395, 0.00951192807406187, -0.015066578984260559, 0.014553842134773731, 0.025742026045918465, 0.01803782396018505, -0.03867877274751663, -0.01965491659939289, 0.013186543248593807, -0.003819233039394021, -0.01590799354016781, -0.008322115056216717, -0.010543975979089737, -0.0021774887572973967, 0.014619577676057816, 0.0033212865237146616, 0.009373883716762066, 0.008479881100356579, 0.006205432116985321, -0.023125752806663513, -0.032788872718811035, 0.022560426965355873, 0.0146853132173419, 0.053009115159511566, 0.018064118921756744, 0.029475802555680275, -0.012095334008336067, -0.03465576097369194, -0.01776173524558544, -0.015947435051202774, -0.0004126957501284778, -0.020391155034303665, -0.02534761279821396, 0.008926882408559322, 0.02316519431769848, -0.01197700947523117, -0.03386693447828293, 0.02169271744787693, 0.022705044597387314, 0.04562044516205788, 0.005972071085125208, -0.008972897194325924, -0.00014708320668432862, 0.000200185168068856, -0.013081366196274757, 0.0174067635089159, -0.00401643943041563, 0.0013599033700302243, 0.011483993381261826, -0.014751048758625984, 0.020391155034303665, -0.0008833209285512567, -0.006067387294024229, 0.013252278789877892, 0.02662288211286068, 0.02043059654533863, -0.027871856465935707, 0.004308962728828192, 0.04149225354194641, -0.003638460533693433, -0.012239951640367508, -0.016092052683234215, -0.015868552029132843, 0.003953990992158651, 0.012424011714756489, -0.011378816328942776, 0.016144640743732452, -0.023572754114866257, 0.014317193999886513, 0.02000988833606243, -0.00023726410290692002, -0.014553842134773731, 0.003891542088240385, -0.03305181488394737, -0.011043565347790718, 0.011260492727160454, 0.007112582214176655, 0.012003304436802864, -0.008092041127383709, 0.010438798926770687, -0.016447024419903755, 0.016460170969367027, -0.007664760574698448, 0.013725574128329754, 0.030106863006949425, -0.005107649136334658, -0.01108958013355732, -0.6188603639602661, -0.012719821184873581, 0.023441283032298088, -0.004716522991657257, 0.02852921187877655, 0.01928679831326008, -0.0010583417024463415, 0.025873497128486633, 0.005426466464996338, 0.012207084335386753, -0.01225967239588499, 0.01943141594529152, 0.0011996730463579297, 0.013528367504477501, 0.014435517601668835, -0.012200510129332542, 0.032368164509534836, -0.0052719879895448685, 0.012936748564243317, -0.013896486721932888, -0.032078929245471954, 0.007454406935721636, -0.01531637366861105, 0.01436978206038475, 0.030159451067447662, 0.015092873014509678, 0.011878406628966331, -0.006027946248650551, -0.019326239824295044, 0.0532720573246479, -0.013002484105527401, 0.03628600016236305, -0.009341015480458736, 0.0023829122073948383, 0.04104525223374367, -0.017866911366581917, -0.009255560114979744, 0.027792973443865776, 0.021442923694849014, 0.037863653153181076, -0.012450305745005608, -0.020798714831471443, 0.004213646054267883, -0.006635999772697687, 0.0013582599349319935, 0.00972228217869997, 0.019957300275564194, -0.00872967578470707, -0.0013048498658463359, 0.0011528364848345518, -0.018931826576590538, -0.0023927725851535797, -0.005301568657159805, 0.017551381140947342, -0.0037534974981099367, 0.011411684565246105, 0.01070831436663866, -0.02584720216691494, 7.076838664943352e-05, -0.002211999846622348, 0.014488106593489647, 0.003094498999416828, -0.020233388990163803, -0.0011717354645952582, -0.03189487010240555, 0.01776173524558544, -0.0343928188085556, 0.007152023259550333, -0.010373063385486603, -0.026793792843818665, -0.009393604472279549, -0.028055915609002113, -0.007171744015067816, 0.01577652245759964, 0.036023057997226715, 0.0022859524469822645, 0.025045229122042656, 0.0033377204090356827, -0.01277898345142603, -0.008749396540224552, 0.005745283327996731, 0.014146281406283379, -0.011247345246374607, -0.009945782832801342, 0.0005698446766473353, -0.0026392806321382523, -0.03055386431515217, -0.009308148175477982, -0.0035497175995260477, -0.04149225354194641, 0.018971268087625504, 0.03328846022486687, 0.0045850519090890884, -0.012732967734336853, -0.008999191224575043, -0.005311429034918547, 0.0027576046995818615, -0.020798714831471443, 0.017156967893242836, -0.006281028036028147, -0.004943310283124447, -0.00452588964253664, 0.011378816328942776, -0.005064920987933874, 0.046251505613327026, -0.0013516864273697138, -0.03365658223628998, -0.022652456536889076, 0.0007617102237418294, -0.007809378672391176, 0.027582619339227676, 0.005870181135833263, 0.0006680371006950736, -0.0032884187530726194, 0.03678559139370918, -0.021232569590210915, -1.8218494005850516e-05, -0.011286786757409573, 0.009682840667665005, -0.008092041127383709, 0.016105199232697487, -0.014304046519100666, 0.01859000138938427, -0.01313395518809557, -0.016170935705304146, 0.04094007611274719, -0.0043845586478710175, -0.009919488802552223, -0.020943332463502884, 0.010649152100086212, -0.019313093274831772, -0.009170103818178177, 0.013830751180648804, -0.016854584217071533, 0.00771077536046505, -0.00242235348559916, 0.02597867324948311, -0.0002902633568737656, 0.021456070244312286, -0.025794614106416702, -0.024532491341233253, 0.013857045210897923, -0.03520793840289116, -0.0038060860242694616, 0.014251458458602428, -0.0034675481729209423, -0.0316845141351223, -0.016525907441973686, -0.0007621210534125566, 0.022310631349682808, 0.012055892497301102, 0.004000005777925253, -0.0015866908943280578, 0.00972228217869997, 0.019273651763796806, 0.005626959726214409, 0.022981133311986923, -0.004769111052155495, -0.030448688194155693, 0.011681200005114079, 0.009419898502528667, -0.007809378672391176, -0.012036171741783619, -0.006731315981596708, 0.009728855453431606, -0.05066893249750137, -0.011359095573425293, 0.01387019269168377, -0.019168473780155182, -0.026741204783320427, -0.003976998385041952, 0.004368124529719353, 0.01154972892254591, -0.025032082572579384, 0.0002797867637127638, 0.0012103550834581256, 0.020943332463502884, -0.008006584830582142, -0.018892385065555573, -0.025452788919210434, 0.0006610527052544057, 0.013462631963193417, -0.014001663774251938, 0.01116846315562725, 0.04133448749780655, 0.01256862934678793, 0.006599845364689827, 0.0329466387629509, -0.027240796014666557, 0.01038621086627245, -0.009446192532777786, 0.022520985454320908, -0.010465092957019806, 0.0005131477955728769, -0.01070831436663866, -0.0168940257281065, -0.011050139553844929, 0.03318328410387039, 0.025834055617451668, 0.023927725851535797, 0.008019732311367989, 0.003308139508590102, 0.015579315833747387, -0.008387850597500801, 0.016670525074005127, -0.03741665184497833, -0.007756790146231651, -0.014027957804501057, 0.011142169125378132, 0.011602316983044147, -0.00769762834534049, -0.023691076785326004, -0.006129836197942495, -0.0031224368140101433, 0.030238334089517593, 0.012049319222569466, -0.020325420424342155, 0.009807738475501537, -0.021745307371020317, 0.014448665082454681, -0.0016655734507367015, 0.013107660226523876, -0.0015990162501111627, -0.015342667698860168, -0.010162710212171078, 0.005360730923712254, 0.003240760648623109, 0.02781926840543747, 0.01556616835296154, -0.01165490597486496, -0.025873497128486633, 0.009038632735610008, -0.018537413328886032, 0.041860371828079224, 0.015000843442976475, -0.025465935468673706, 0.003937556874006987, -0.01697290875017643, 0.01711752638220787, 0.00494988402351737, -0.005252267234027386, 0.0030780653469264507, 0.005807732231914997, -0.009860326535999775, 0.009853753261268139, 0.029318036511540413, 0.005153663922101259, 0.005081355106085539, -0.039967190474271774, 0.011207904666662216, -0.03781106323003769, -0.006277740933001041, -0.0061561306938529015, -0.0020164367742836475, -0.00039256425225175917, -0.03838953748345375, 0.0003944130439776927, 0.011109300889074802, 0.016644230112433434, 0.01928679831326008, 0.008216938935220242, 0.03478723019361496, -0.01436978206038475, 0.016775701195001602, 0.02387513779103756, -0.018905531615018845, -0.0016762554878368974, -0.02979133278131485, -0.030054274946451187, 0.0012333624763414264, -0.008092041127383709, -0.03696965053677559, 0.004164344631135464, -0.02288910374045372, 0.001657356508076191, -0.013567809015512466, 0.016118347644805908, -0.017919499427080154, 0.021876778453588486, -0.023717371746897697, -0.003651607548817992, -0.040046073496341705, 0.008197218179702759, 0.019115885719656944, 0.009064926765859127, -0.02992280386388302, -0.02958097867667675, 0.006527536083012819, -0.0333673432469368, 0.03231557831168175, -0.008677086792886257, 0.013442912138998508, -0.010057533159852028, 0.011129021644592285, -0.04709291830658913, -0.02521614171564579, 0.028292562812566757, 0.004476588219404221, 0.010820064693689346, -0.024282697588205338, 0.001700906315818429, -0.013337735086679459, -0.0036779018118977547, -0.013962222263216972, 0.012180790305137634, 0.0032686982303857803, -0.001339360955171287, -0.005087928380817175, 0.010340196080505848, -0.017301585525274277, -0.01859000138938427, -0.005801158491522074, -0.01881350204348564, -0.019970448687672615, -0.020088771358132362, -0.009032059460878372, -0.011319654993712902, -0.03150045499205589, 0.02421696111559868, 0.016933467239141464, -0.008387850597500801, 0.01531637366861105, -0.011990156956017017, -0.001756781479343772, 0.056164421141147614, -0.032788872718811035, 0.016867732629179955, -0.01345605868846178, 0.014948254451155663, 0.015106020495295525, -0.025176700204610825, -0.007618745323270559, 0.003674614941701293, -0.002877571852877736, 0.022994281724095345, -0.005156950559467077, 0.013528367504477501, 0.0056138127110898495, 0.01345605868846178, 0.0007239123224280775, -0.011891554109752178, -0.03662782534956932, 0.03368287533521652, -0.01965491659939289, -0.011240771971642971, -0.010596564039587975, 0.015211196616292, 0.024006608873605728, 0.008184070698916912, 0.012404290959239006, 0.014974549412727356, -0.0002660233876667917, 0.04125560447573662, -0.014566988684237003, -0.007336082868278027, -0.009242412634193897, -0.009268706664443016, -0.009465913288295269, 0.0070534199476242065, 0.0333673432469368, 0.005196392070502043, 0.0006548900273628533, -0.0008381277439184487, 0.02958097867667675, 0.015276932157576084, 0.02156124636530876, 0.014803636819124222, -0.005439613480120897, 0.0007966322009451687, -0.01571078598499298, 0.0004112577880732715, 0.011359095573425293, -0.010839785449206829, -0.013988516293466091, 0.048039510846138, 0.009163529612123966, -0.026649175211787224, -0.004213646054267883, 0.021377187222242355, -0.002491375897079706, 0.007316362112760544, 0.017998382449150085, 0.01091209426522255, 0.0009383743745274842, 0.0076516130939126015, -0.018405942246317863, 0.003217753255739808, -0.010760903358459473, -0.018497971817851067, -0.014448665082454681, -0.03544458746910095, -0.008400998078286648, -0.022507838904857635, -0.00972228217869997, -0.025110963732004166, -0.008604777976870537, -0.031184924766421318, -0.041939254850149155, -0.006050953641533852, 0.010373063385486603, 0.032078929245471954, -0.023861989378929138, -0.01816929504275322, 0.004884148482233286, -0.005702555645257235, -0.023546459153294563, 0.012483173049986362, 0.0014691886026412249, -0.014001663774251938, 0.026859529316425323, 0.009347589686512947, -0.01929994486272335, 0.0007009048713371158, -0.008532469160854816, 0.023349253460764885, 0.013291720300912857, 0.012384570203721523, -0.00484470697119832, -0.0008923595305532217, 0.0003989323740825057, 0.0036779018118977547, 0.0100706797093153, -0.007506994996219873, 0.01320626400411129, 0.020101917907595634, -0.028634387999773026, 0.0032078928779810667, -0.024032901972532272, 0.00605424027889967, 0.013462631963193417, 0.014343488030135632, 0.009209545329213142, -0.020732980221509933, 0.016157789155840874, 0.023125752806663513, -0.0102810338139534, 0.0067641837522387505, -0.019746946170926094, 0.029055094346404076, 0.02508467063307762, -0.018511120229959488, 0.014843078330159187, -0.014238310977816582, 0.015368961729109287, -0.01116846315562725, -0.01972065307199955, 0.029133977368474007, 0.03181598708033562, -0.004308962728828192, 0.0049301632679998875, -0.013160249218344688, -0.024322139099240303, -0.023283516988158226, -0.011345949023962021, 0.0012539048912003636, 0.015250638127326965, -0.022100279107689857, -0.014290899969637394, -0.007211185526102781, -0.0077304961159825325, 0.0006622852524742484, 5.674823114532046e-05, 5.613196117337793e-05, -0.03273628279566765, -0.01598687656223774, 0.003385378746315837, -0.00943961925804615, -0.009268706664443016, -0.009380456991493702, -0.024558786302804947, -0.0144749591127038, -0.008650792762637138, -0.007467553950846195, 0.01676255464553833, 0.008052599616348743, 0.0068496400490403175, 0.0032391173299402, 0.0008114227093756199, 0.00536730419844389, -0.02647826261818409, -0.004894008859992027, 0.01384389866143465, 0.05319317430257797, 0.016460170969367027, 0.026149585843086243, 0.018327059224247932, 0.02028597891330719, 0.010971256531774998, 0.002340184058994055, -0.006974537391215563, -0.021732158958911896, 0.007750216405838728, -0.0321052223443985, 0.02649141103029251, -7.328482024604455e-05, 0.02133774571120739, 0.03647005930542946, 0.027871856465935707, 0.0018718186765909195, 0.032236695289611816, -0.006829919293522835, -0.0048742881044745445, -0.025518525391817093, 0.012325407937169075, 0.006350050214678049, -0.02564999647438526, 0.010142989456653595, -0.026110144332051277, 0.011457699351012707, -0.01818244159221649, 0.0074478331953287125, -0.020299125462770462, 0.01656534895300865, -0.017091233283281326, 0.03234187141060829, -0.054691944271326065, 0.0045357500202953815, 0.025097817182540894, 0.011207904666662216, 0.002356617944315076, -0.01831391267478466, 0.011871833354234695, -0.013554662466049194, 0.0065045286901295185, 0.0259129386395216, 0.007257200311869383, -0.022152867168188095, 7.585261482745409e-05, -0.004394419025629759, 0.019957300275564194, -0.026741204783320427, -0.018511120229959488, 0.010136415250599384, -0.014843078330159187, -0.018287619575858116, -0.015960581600666046, -0.028792154043912888, -0.045541562139987946, 0.017801176756620407, 0.00291372649371624, -0.015960581600666046, 0.02352016605436802, 0.0075858780182898045, -0.018327059224247932, -0.010189004242420197, 0.03008056990802288, 0.003365657990798354, 0.011746935546398163, 0.040808603167533875, 0.02845032885670662, -0.003566151484847069, -0.021863630041480064, 0.01317339576780796, 0.010136415250599384, -0.01411998737603426, -0.013804457150399685, 0.02697785384953022, -0.012529187835752964, -0.02041744999587536, 0.0008126552565954626, -0.00043467606883496046, 0.004516029730439186, 0.00121446349658072, 0.033209580928087234, -0.006599845364689827, 0.001328679034486413, 0.010228444822132587, -0.0059030489064753056, -0.014908813871443272, 0.0415448434650898, -0.008230085484683514, -0.0014864442637190223, -0.012233378365635872, -0.03683818131685257, -0.0057617174461483955, -0.006731315981596708, -0.010044385679066181, 0.02823997475206852, 0.021995101124048233, -0.020601509138941765, -0.004305676091462374, -0.00018837332027032971, -0.007441259454935789, 0.010162710212171078, -0.014251458458602428, 0.03263110667467117, -0.005705842282623053, 0.0037403504829853773, 0.005886614788323641, 0.005114222411066294, 0.0039014024659991264, 0.0055086356587708, 0.002478228649124503, 0.03731147572398186, -0.004811839200556278, 0.009571090340614319, -0.007230905815958977, 0.0390205979347229, 0.013646692037582397, 0.0017058365046977997, -0.005393598694354296, -0.0065604038536548615, -0.002351687755435705, -0.00979459099471569, -0.00992606207728386, -0.005728849675506353, -0.01999674178659916, -0.006678727921098471, -0.03728518262505531, 0.0005131477955728769, -0.02626791037619114, 0.011240771971642971, 0.012253099121153355, 0.04065084084868431, -0.011852112598717213, -0.019194768741726875, -0.013699280098080635, 0.02550537697970867, -0.014106839895248413, -0.023927725851535797, -0.0018340207170695066, 0.0029515244532376528, -0.014527547173202038, 0.013962222263216972, -0.008972897194325924, 0.00972228217869997, -0.01197700947523117, 0.007493847981095314, 0.013147101737558842, -0.0069022285751998425, 0.019326239824295044, -0.008197218179702759, -0.00034696023794822395, -0.01697290875017643, -0.011490566655993462, -0.0004018082981929183, 0.011240771971642971, -0.00064708391437307, 0.01782746985554695, 0.007881687954068184, 0.013094513677060604, -0.019917858764529228, -0.010261313058435917, -0.006008225493133068, 0.014751048758625984, 0.026820087805390358, 0.028713271021842957, -0.02500578761100769, -0.036654118448495865, -0.0021626981906592846, -0.006290888413786888, -0.01632869988679886, -0.036443766206502914, -0.014041105285286903, 0.0005879219388589263, 0.020470038056373596, -0.0024683682713657618, -0.027135618031024933, 0.021600687876343727, -0.017485644668340683, -0.028082210570573807, 0.005626959726214409, 0.009557942859828472, 0.004443720448762178, 0.002963028149679303, 0.033551402390003204, -0.003569438122212887, 0.004377984907478094, -0.01045851968228817, 0.005357443820685148, -0.0031733817886561155, -0.0168940257281065, -0.000456450943602249, 0.006609705276787281, -0.027293384075164795, 0.033709168434143066, 0.0060213725082576275, -0.024637669324874878, -0.01978638768196106, 0.00844701286405325, -0.02958097867667675, 0.0014954828657209873, 0.017288438975811005, 0.015500432811677456, 0.005041913595050573, -0.005380451679229736, 0.005949063692241907, 0.026373086497187614, -0.008368130773305893, 0.006566977594047785, -0.006843066308647394, -0.02175845392048359, -0.0057650040835142136, -0.0075858780182898045, -0.0038258065469563007, -0.028003327548503876, -0.022244896739721298, -0.012838144786655903, 0.013278572820

In [5]:
data = [
    '주식 시장이 급등했어요',
    '시장 물가가 올랐어요',
    '전통 시장에는 다양한 물품들을 팔아요',
    '부동산 시장이 점점 더 복잡해지고 있어요',
    '저는 빠른 비트를 좋아해요',
    '최근 비트코인 가격이 많이 변동했어요',
]
df = pd.DataFrame(data, columns=['text'])
df

                     text
0            주식 시장이 급등했어요
1             시장 물가가 올랐어요
2    전통 시장에는 다양한 물품들을 팔아요
3  부동산 시장이 점점 더 복잡해지고 있어요
4          저는 빠른 비트를 좋아해요
5    최근 비트코인 가격이 많이 변동했어요

In [6]:
# 텍스트를 임베딩 벡터로 변환하는 함수 정의
def get_embedding(text: str):
  return embeddings.embed_query(text)

# DataFrame의 각 행에 대해 'text' 열의 내용을 임베딩 벡터로 변환
df['embedding'] = df.apply(lambda row: get_embedding(
        row.text,
    ), axis=1)

# 변환된 DataFrame 출력
df

                     text                                          embedding
0            주식 시장이 급등했어요  [-0.01370231993496418, -0.035045821219682693, ...
1             시장 물가가 올랐어요  [-0.00015702718519605696, -0.03539642691612243...
2    전통 시장에는 다양한 물품들을 팔아요  [-0.009272306226193905, -0.01461657416075468, ...
3  부동산 시장이 점점 더 복잡해지고 있어요  [-0.017441052943468094, -0.0031565295066684484...
4          저는 빠른 비트를 좋아해요  [-0.03796839341521263, -0.013386794365942478, ...
5    최근 비트코인 가격이 많이 변동했어요  [-0.01749446988105774, -0.021561449393630028, ...

In [7]:
def cos_sim(A: np.ndarray, B: np.ndarray):
    return dot(A, B)/(norm(A)*norm(B))

def return_answer_candidate(df: pd.DataFrame, query: str):
    # 쿼리 텍스트를 임베딩 벡터로 변환
    query_embedding = get_embedding(query)

    # DataFrame의 각 문서 임베딩과 쿼리 임베딩 간의 유사도 계산
    df["similarity"] = df.embedding.apply(lambda x: cos_sim(np.array(x), np.array(query_embedding)))

    # 유사도가 높은 순으로 정렬하고 상위 3개 문서 선택
    top_three_doc = df.sort_values("similarity", ascending=False).head(3)

    return top_three_doc

In [8]:
return_answer_candidate(df, "과일 값이 비싸다.")

,text,embedding,similarity
2,전통 시장에는 다양한 물품들을 팔아요,"[-0.009272306226193905, -0.01461657416075468, ...",0.824548
1,시장 물가가 올랐어요,"[-0.00015702718519605696, -0.03539642691612243...",0.814571
0,주식 시장이 급등했어요,"[-0.01370231993496418, -0.035045821219682693, ...",0.805389

In [13]:
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name='BAAI/bge-m3')

# 데이터셋 생성
data = [
    '주식 시장이 급등했어요',
    '시장 물가가 올랐어요',
    '전통 시장에는 다양한 물품들을 팔아요',
    '부동산 시장이 점점 더 복잡해지고 있어요',
    '저는 빠른 비트를 좋아해요',
    '최근 비트코인 가격이 많이 변동했어요',
]
df = pd.DataFrame(data, columns=['text'])

# DataFrame의 각 행을 벡터로 변환
df['embedding'] = df['text'].apply(get_embedding)
df

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 54645.73it/s]

                     text                                          embedding
0            주식 시장이 급등했어요  [-0.028310662135481834, -0.002016831422224641,...
1             시장 물가가 올랐어요  [0.0039781262166798115, 0.02656499482691288, -...
2    전통 시장에는 다양한 물품들을 팔아요  [0.00010136908531421795, 0.0005807465640828013...
3  부동산 시장이 점점 더 복잡해지고 있어요  [-0.0077268569730222225, 0.021975155919790268,...
4          저는 빠른 비트를 좋아해요  [-0.019412294030189514, 0.012223096564412117, ...
5    최근 비트코인 가격이 많이 변동했어요  [-0.026391318067908287, -0.00452756742015481, ...

In [14]:
sim_result = return_answer_candidate(df, '과일 값이 비싸다')
sim_result

,text,embedding,similarity
1,시장 물가가 올랐어요,"[0.0039781262166798115, 0.02656499482691288, -...",0.642563
5,최근 비트코인 가격이 많이 변동했어요,"[-0.026391318067908287, -0.00452756742015481, ...",0.604495
0,주식 시장이 급등했어요,"[-0.028310662135481834, -0.002016831422224641,...",0.575970